pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io
import qs.utils

// Reads the live monitor list and applies an arrangement by writing ~/.config/hypr/monitors.conf
// then `hyprctl reload`. It NEVER issues live `hyprctl keyword monitor` commands (safer — a bad
// one can blank the screen); the worst case is a bad monitors.conf, recoverable from the .bak it
// keeps or by re-running nwg-displays.
Singleton {
    id: root

    property var monitors: []
    readonly property string confPath: `${Paths.home}/.config/hypr/monitors.conf`

    function refresh(): void {
        proc.running = false;
        proc.running = true;
    }

    // lines: array of "monitor=..." strings
    function applyLines(lines: var): void {
        const content = "# Generated by the caelestia Display pane. Do not edit manually.\n\n" + lines.join("\n") + "\n";
        Quickshell.execDetached(["sh", "-c", 'f="$1"; [ -f "$f" ] && [ ! -f "$f.bak" ] && cp "$f" "$f.bak"; printf "%s" "$2" > "$f"; hyprctl reload', "sh", root.confPath, content]);
        Qt.callLater(root.refresh);
    }

    Component.onCompleted: refresh()

    Process {
        id: proc

        command: ["hyprctl", "monitors", "all", "-j"]
        stdout: StdioCollector {
            onStreamFinished: {
                try {
                    root.monitors = JSON.parse(text);
                } catch (e) {
                    root.monitors = [];
                }
            }
        }
    }
}
