#!/usr/bin/env fish
# workspace-mode.fish [separate|shared]
#   separate = per-monitor workspaces (ws 1-10 -> $mon1, 11-20 -> $mon2)
#   shared   = Hyprland default (workspaces float across monitors)
# Regenerates ~/.config/caelestia/workspace-split.conf (sourced by hypr-user.conf), writes the
# monitor->base map read by wsaction.fish, relocates existing workspaces, then reloads.
# To change which monitor owns which range, edit $mon1/$mon2 below.

set -l conf $HOME/.config/caelestia/workspace-split.conf
set -l state $HOME/.config/caelestia/workspace-mode
set -l map $HOME/.config/caelestia/workspace-monitors
set -l mon1 HDMI-A-2
set -l mon2 eDP-1

set -l mode $argv[1]
test -z "$mode"; and set mode (cat $state 2>/dev/null)
test -z "$mode"; and set mode separate

if test "$mode" = separate
    begin
        echo "# Generated by workspace-mode.fish — do not edit by hand."
        echo "# mode: separate (per-monitor workspaces)"
        for i in (seq 1 10)
            test $i -eq 1; and echo "workspace = $i, monitor:$mon1, default:true"; or echo "workspace = $i, monitor:$mon1"
        end
        for i in (seq 11 20)
            test $i -eq 11; and echo "workspace = $i, monitor:$mon2, default:true"; or echo "workspace = $i, monitor:$mon2"
        end
    end >$conf
    # monitor -> base (wsaction reads this)
    printf '%s 0\n%s 10\n' $mon1 $mon2 >$map
    echo separate >$state
    hyprctl reload >/dev/null 2>&1
    # relocate any EXISTING workspaces into the right monitor block (rules only bind at creation)
    for w in (hyprctl workspaces -j | jq -r '.[].id')
        if test $w -ge 1 -a $w -le 10
            hyprctl dispatch moveworkspacetomonitor "$w $mon1" >/dev/null 2>&1
        else if test $w -ge 11 -a $w -le 20
            hyprctl dispatch moveworkspacetomonitor "$w $mon2" >/dev/null 2>&1
        end
    end
else
    begin
        echo "# Generated by workspace-mode.fish — do not edit by hand."
        echo "# mode: shared (Hyprland default; no per-monitor binding)"
    end >$conf
    rm -f $map
    echo shared >$state
    hyprctl reload >/dev/null 2>&1
end
