#!/usr/bin/env fish
# workspace-mode.fish [separate|shared]
#   separate = per-monitor workspaces (ws 1-10 -> HDMI-A-2, 11-20 -> eDP-1)
#   shared   = Hyprland default (workspaces float across monitors)
# Regenerates ~/.config/caelestia/workspace-split.conf (sourced by hypr-user.conf) and reloads.
# To change which monitor owns which range, edit $mon1/$mon2 below.

set -l conf $HOME/.config/caelestia/workspace-split.conf
set -l state $HOME/.config/caelestia/workspace-mode
set -l mon1 HDMI-A-2
set -l mon2 eDP-1

set -l mode $argv[1]
test -z "$mode"; and set mode (cat $state 2>/dev/null)
test -z "$mode"; and set mode separate

if test "$mode" = separate
    begin
        echo "# Generated by workspace-mode.fish — do not edit by hand."
        echo "# mode: separate (per-monitor workspaces)"
        for i in (seq 1 10)
            test $i -eq 1; and echo "workspace = $i, monitor:$mon1, default:true"; or echo "workspace = $i, monitor:$mon1"
        end
        for i in (seq 11 20)
            test $i -eq 11; and echo "workspace = $i, monitor:$mon2, default:true"; or echo "workspace = $i, monitor:$mon2"
        end
    end >$conf
    echo separate >$state
else
    begin
        echo "# Generated by workspace-mode.fish — do not edit by hand."
        echo "# mode: shared (Hyprland default; no per-monitor binding)"
    end >$conf
    echo shared >$state
end

hyprctl reload >/dev/null 2>&1
